// <Route path="/bebidas" component={ Drinks } />
// <Route path="/comidas/{id-da-receita}" component={ FoodDetails } />
// <Route path="/bebidas/{id-da-receita}" component={ DrinkDetails } />
// <Route path="/comidas/{id-da-receita}/in-progress" component={ FoodProgress } />
// <Route path="/bebidas/{id-da-receita}/in-progress" component={ DrinkProgress } />
// <Route path="/explorar" component={ Explore } />
// <Route path="/explorar/comidas" component={ FoodExplore } />
// <Route path="/explorar/bebidas" component={ DrinkExplore } />
// <Route path="/explorar/comidas/ingredientes" component={ FoodIngredientExplore } />
// <Route path="/explorar/bebidas/ingredientes" component={ DrinkIngredientExplore } />
// <Route path="/explorar/comidas/area" component={ FoodArea } />
// <Route path="/perfil" component={ Profile } />
// <Route path="/receitas-feitas" component={ RecipesDone } />
// <Route path="/receitas-favoritas" component={ FavoriteRecipes } />
